# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'h:\接单\1958756124713311871人力资源管理软件\XuanYuRecruit/ui/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWidget(object):
    def setupUi(self, LoginWidget):
        LoginWidget.setObjectName("LoginWidget")
        LoginWidget.resize(880, 560)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoginWidget.sizePolicy().hasHeightForWidth())
        LoginWidget.setSizePolicy(sizePolicy)
        LoginWidget.setMinimumSize(QtCore.QSize(880, 560))
        LoginWidget.setMaximumSize(QtCore.QSize(880, 650))
        self.label = QtWidgets.QLabel(LoginWidget)
        self.label.setGeometry(QtCore.QRect(0, 130, 880, 464))
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setPixmap(QtGui.QPixmap(":/login/img/bg03.png"))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(LoginWidget)
        self.label_2.setGeometry(QtCore.QRect(-55, 181, 551, 409))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/login/img/bg01.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(LoginWidget)
        self.label_3.setGeometry(QtCore.QRect(-45, 75, 374, 183))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/login/img/bg02.png"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(LoginWidget)
        self.label_4.setGeometry(QtCore.QRect(9, 23, 187, 46))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/login/img/logo.png"))
        self.label_4.setObjectName("label_4")
        self.logWidget = QtWidgets.QWidget(LoginWidget)
        self.logWidget.setGeometry(QtCore.QRect(490, 50, 331, 421))
        self.logWidget.setObjectName("logWidget")
        self.regWidget = QtWidgets.QWidget(LoginWidget)
        self.regWidget.setGeometry(QtCore.QRect(480, 50, 331, 421))
        self.regWidget.setObjectName("regWidget")
        self.msgWidget = MessageLabel(LoginWidget)
        self.msgWidget.setGeometry(QtCore.QRect(250, 25, 380, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msgWidget.sizePolicy().hasHeightForWidth())
        self.msgWidget.setSizePolicy(sizePolicy)
        self.msgWidget.setStyleSheet("")
        self.msgWidget.setObjectName("msgWidget")

        self.retranslateUi(LoginWidget)
        QtCore.QMetaObject.connectSlotsByName(LoginWidget)

    def retranslateUi(self, LoginWidget):
        _translate = QtCore.QCoreApplication.translate
        LoginWidget.setWindowTitle(_translate("LoginWidget", "轩雨招聘登录"))
from components.messagelabel import MessageLabel
from resource.qrc import loginQrc_rc
