# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'h:\接单\1958756124713311871人力资源管理软件\XuanYuRecruit/ui/login_log.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_log(object):
    def setupUi(self, log):
        log.setObjectName("log")
        log.resize(313, 339)
        self.accountLineEdit = QtWidgets.QLineEdit(log)
        self.accountLineEdit.setGeometry(QtCore.QRect(55, 80, 255, 39))
        self.accountLineEdit.setObjectName("accountLineEdit")
        self.pwdLabel = QtWidgets.QLabel(log)
        self.pwdLabel.setGeometry(QtCore.QRect(3, 156, 36, 26))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        font.setPointSize(10)
        self.pwdLabel.setFont(font)
        self.pwdLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pwdLabel.setObjectName("pwdLabel")
        self.loginBtn = QtWidgets.QPushButton(log)
        self.loginBtn.setGeometry(QtCore.QRect(55, 283, 255, 40))
        self.loginBtn.setObjectName("loginBtn")
        self.pwdLineEdit = QtWidgets.QLineEdit(log)
        self.pwdLineEdit.setGeometry(QtCore.QRect(55, 150, 255, 39))
        self.pwdLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwdLineEdit.setObjectName("pwdLineEdit")
        self.loginTopic = QtWidgets.QLabel(log)
        self.loginTopic.setGeometry(QtCore.QRect(110, 0, 144, 52))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.loginTopic.setFont(font)
        self.loginTopic.setAlignment(QtCore.Qt.AlignCenter)
        self.loginTopic.setObjectName("loginTopic")
        self.accountLabel = QtWidgets.QLabel(log)
        self.accountLabel.setGeometry(QtCore.QRect(3, 87, 36, 26))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        font.setPointSize(10)
        self.accountLabel.setFont(font)
        self.accountLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.accountLabel.setObjectName("accountLabel")
        self.transToRegisterBtn = QtWidgets.QPushButton(log)
        self.transToRegisterBtn.setGeometry(QtCore.QRect(246, 220, 64, 24))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        self.transToRegisterBtn.setFont(font)
        self.transToRegisterBtn.setObjectName("transToRegisterBtn")
        self.remindPwdCheckBox = QtWidgets.QCheckBox(log)
        self.remindPwdCheckBox.setGeometry(QtCore.QRect(3, 220, 91, 24))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        self.remindPwdCheckBox.setFont(font)
        self.remindPwdCheckBox.setObjectName("remindPwdCheckBox")
        self.accountTip = QtWidgets.QLabel(log)
        self.accountTip.setGeometry(QtCore.QRect(55, 62, 251, 16))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        font.setPointSize(8)
        self.accountTip.setFont(font)
        self.accountTip.setText("")
        self.accountTip.setObjectName("accountTip")
        self.pwdTip = QtWidgets.QLabel(log)
        self.pwdTip.setGeometry(QtCore.QRect(55, 131, 251, 16))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        font.setPointSize(8)
        self.pwdTip.setFont(font)
        self.pwdTip.setText("")
        self.pwdTip.setObjectName("pwdTip")

        self.retranslateUi(log)
        QtCore.QMetaObject.connectSlotsByName(log)

    def retranslateUi(self, log):
        _translate = QtCore.QCoreApplication.translate
        log.setWindowTitle(_translate("log", "Form"))
        self.pwdLabel.setText(_translate("log", "密码"))
        self.loginBtn.setText(_translate("log", "登  录"))
        self.loginTopic.setText(_translate("log", "用户登录"))
        self.accountLabel.setText(_translate("log", "账号"))
        self.transToRegisterBtn.setText(_translate("log", "注册账号"))
        self.remindPwdCheckBox.setText(_translate("log", "记住密码"))
